### ISSUE TITLE
versions 1.6.4, 1.7.10, 1.8.x, 1.16.1, & 1.16.5 target java 17 instead of 8

### ISSUE THREAD

**Issue by IronstarkMC** [Minecraft-Java-Edition-Speedrunning/set-spawn#1]
When I try open Minecraft it crash. I tried many things; but nothing works

https://user-images.githubusercontent.com/121715518/210133279-34bc8dae-9863-49e8-bc06-991e97259a44.mp4

**Comment by tildejustin** [comment]
versions 1.6.4, 1.7.10, 1.8.x, 1.16.1, & 1.16.5 all target java 17 when they should be targetting java 8

**Comment by tildejustin** [comment]
fixed in
- #2 
- #3 
- #4 
- #5 
- #6
