### ISSUE TITLE
1.21 crash error. Please help.

### ISSUE THREAD

**Issue by Lazerbrainzz** [Minecraft-Java-Edition-Speedrunning/set-spawn#10]
#### Instructions

This is a template for the issue you are about to open! It will help you provide the information necessary
to complete your **crash report**. Before you open an issue, ensure you've completed every step on the checklist below.

- Have you used the search tool to find similar issues? Make sure you are not opening a duplicate.
- Are you using the latest version of the mod? If not, try updating to see if it resolves your issue.

All good? Please read through the sections below, and fill out any lines starting with an arrow. Then, remove
everything above this dashed line (including the line itself.)

------------------------

### Version

1.21

### Reproduction Steps

get setspawn mod
try to load a world with atum(I'm using the seed [1145141919016166331])
game crash

### Crash Report File
[crash-2024-08-02_13.36.54-server.txt](https://github.com/user-attachments/files/16473584/crash-2024-08-02_13.36.54-server.txt)

### Additional Information

idk if there's anything else I don't think so though

**Comment by tildejustin** [comment]
use fabric loader 0.16+, it's a weird mixin bug
